# Handling Arrays with NumPy

## Single Dimensional Arrays

In [7]:
import numpy as np

np_array = np.array([5, 10, 15, 25, 30])

print("--0--")
print(np.unique(np_array))

print("--1--")
print(np.std(np_array))

print("--2--")
print(np_array.max())

print("--3--")
print(np_array ** 2)

print("--4--")
print(np_array + np_array)

print("--5--")
print(np.sum(np_array ** 2))

print("--6--")
print(np_array.shape)

--0--
[ 5 10 15 25 30]
--1--
9.273618495495704
--2--
30
--3--
[ 25 100 225 625 900]
--4--
[10 20 30 50 60]
--5--
1875
--6--
(5,)


## Two Dimensional Arrays

In [11]:
import numpy as np

print("--0--")
np_2d_array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print(np_2d_array)

print("--1--")
np_2d_array_T = np_2d_array.T
print(np_2d_array_T)

print("--2--")
print(np_2d_array.shape)

print("--3--")
print(np_2d_array[1,1])
print(np_2d_array[0,2])

--0--
[[1 2 3]
 [4 5 6]]
--1--
[[1 4]
 [2 5]
 [3 6]]
--2--
(2, 3)
--3--
5
3


# Important Functionalities

## Calculating Dot Product

In [12]:
import numpy as np

np_array = np.array([5, 10, 15, 20, 25, 30])
dot_product = np.dot(np_array, np_array)
print(dot_product)

2275


## Generating Random Values

In [13]:
import numpy as np

print("--0--")
print(np.random.rand())

print("--1--")
print(np.random.rand(3, 2))

--0--
0.67094064707494
--1--
[[0.15021107 0.42001976]
 [0.10911861 0.20459247]
 [0.31925601 0.73801048]]


In [17]:
import numpy as np

print("--0--")
print(np.random.randint(5, 15, 2))

print("--1--")
print(np.random.randint(5, 15, (3, 2)))

--0--
[ 5 14]
--1--
[[ 7  6]
 [10 11]
 [ 5 10]]


## Sampling the Data

In [19]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])

print("--0--")
print(np.random.choice(array, 10, replace=True))

print("--1--")
print(np.random.choice(array, 3, replace=False))

--0--
[2 5 3 1 1 4 3 4 2 3]
--1--
[5 2 3]


## Randomly Shuffling Values

In [21]:
import numpy as np

x = [1, 2, 3, 4, 5]
np.random.shuffle(x)

print(x)

[5, 1, 2, 4, 3]
